### ISSUE TITLE
Question: purpose of consult-org-roam-file-find

### ISSUE THREAD

**Issue by albertfgu** [jgru/consult-org-roam#15]
Thanks for this package! All of the provided functionality looks very useful, but I'm a little confused about the purpose of `consult-org-roam-file-find`. It seems to do the same thing as the normal `org-roam-node-find` with `consult-org-roam-mode` turned on; both of them search through the org-roam notes with consult completing. Just want to understand if I'm missing anything.

**Comment by jgru** [comment]
Hi @alberfgu, 


> Thanks for this package! All of the provided functionality looks very
> useful, 

Thank you, good to hear. 

> but I'm a little confused about the purpose of
> `consult-org-roam-file-find`. It seems to do the same thing as the
> normal `org-roam-node-find` with `consult-org-roam-mode` turned on;
> both of them search through the org-roam notes with consult
> completing. Just want to understand if I'm missing anything.

`consult-org-roam-file-find` searches, previews and opens files within the `org-roam-directory`.

`org-roam-node-find` with `consult-org-roam-mode` searches and previews single `org-roam`-nodes. Since there might be several nodes within one (potentially) large org-file this provides a more precise search and resembles `org-roam-node-find`'s functionality.

If you have any further questions, do not hesitate to pose them. 

HTH. 

Best regards,
jgru

**Comment by albertfgu** [comment]
Thanks for the clarification, that's what I suspected. Since I generally don't use nodes for headings (i.e. one per file) they seem functionally equivalent to me. As a minor suggestion, the UI for `consult-org-roam-file-find` is a little clunkier because it keeps the full file path instead of the relative path to the `org-roam-directory`:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/8164679/197018259-cfa49392-c68a-456e-b7a0-b58ede392d3d.png">

vs. `org-roam-node-find`:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/8164679/197018346-a4db63a6-04c7-4f05-8234-c0b46c85613e.png">

Anyways, thanks again for the package, it's working really well!

**Comment by jgru** [comment]
Hi @albertfgu,

happy to hear that you like the package! Displaying the path is needed to use the function `consult--file-preview`. I opened a corresponding issue  #16 to enhance this function. We would need to use an alist mapping filenames to full paths I suppose.
