### ISSUE TITLE
`org-roam-node-insert` failed to insert into correct place.

### ISSUE THREAD

**Issue by colawithsauce** [jgru/consult-org-roam#23]
### Descriptions
 https://github.com/org-roam/org-roam/issues/2311

### Screen cast
[Screencast from 2023-01-30 11-59-54.webm](https://user-images.githubusercontent.com/51731521/215384908-a5f6ed18-ad5f-4341-85b2-c27b6938025c.webm)

**Comment by jgru** [comment]
Hi @colawithsauce,

thanks for opening this issue. 

I believe that this issue has been fixed in commit https://github.com/jgru/consult-org-roam/commit/a7d51008e43d438ff94d6445a81040e397300c77 as tracked in https://github.com/jgru/consult-org-roam/issues/17.

Could you please install the HEAD of this repo, try again and report whether this resolved your issue or not?

The installation could be done like so:
```elisp
(use-package consult-org-roam
   :straight (:host github :repo "jgru/consult-org-roam")
   :after org-roam
   :init
   (require 'consult-org-roam)
   (consult-org-roam-mode 1))
```

Thanks. 

Best regards,
jgru

**Comment by colawithsauce** [comment]
Oh, yes. It had been fixed, and I didn't noticed it.
